image: debian/stretch
packages:
  - curl
environment:
  PACKAGES: media-tv/plex-media-server
sources:
  - https://git.sr.ht/~fkmclane/overlay
tasks:
  - bootstrap: |
       cd overlay
       sudo -E .ci/bootstrap.sh ../prefix
  - test: |
       cd overlay
       sudo -E .ci/test.sh ../prefix
  - build: |
       cd overlay
       sudo -E .ci/build.sh ../prefix
