language: bash
sudo: required

jobs:
  include:
    - stage: setup
      script: sudo ./.ci/setup.sh

    - stage: test
      script: sudo ./.ci/test.sh

    - stage: build
      script: sudo ./.ci/build.sh
      env:
        - PACKAGES="app-admin/pass-otp app-misc/{blinkstick,cronic,gotty-bin,tty-clock,wemux} app-shells/elvish"
        - PACKAGES="app-admin/linode-cli:{0,4}"
        - PACKAGES="dev-embedded/{arduino-bin,energia-bin,teensyduino-bin} dev-python/{pandocfilters,slixmpp}"
        - PACKAGES="dev-python/{twilio,vex} net-p2p/zget"
        - PACKAGES="games-action/armagetronad-dedicated"
        - PACKAGES="games-arcade/nsnake games-misc/{git-fire,lolcat,nyancat,pipes}"
        - PACKAGES="media-libs/openvr media-sound/ympd media-tv/plex-media-server"
        - PACKAGES="net-fs/pingfs net-mail/syncmaildir"
        - PACKAGES="net-wireless/create_ap sci-physics/chipmunk"
        - PACKAGES="sci-electronics/fritzing-bin"
        - PACKAGES="sys-apps/petty sys-kernel/pf-sources www-servers/pagekite sys-boot/{mkusb,mkwin} sys-fs/pifs"
        - PACKAGES="x11-misc/{clipster,lemonbar} x11-themes/arc-openbox-theme"
        - PACKAGES="x11-misc/barline"
